Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using rocket_elevators_customer_portal.Models;
using System.Net.Http;
using System.IO;
using System.Net;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

// using APIConsume.Models;

using Newtonsoft.Json;


namespace rocket_elevators_customer_portal.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InterventionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Net.Http;
using Newtonsoft.Json;
using rocket_elevators_customer_portal.Models;
using System.Dynamic;

// reference https://www.yogihosting.com/aspnet-core-consume-api/

namespace RocketElevatorsCustomerPortal.Controllers
{
    public class InterventionController : Controller
    {
       [HttpPost]
       public ActionResult AddIntervention(IEnumerable<Intervention> interfaces)
       {
           return View();
       }
       
        public async Task<IActionResult> IndexAsync()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.Buildings = await GetBuildings();
            mymodel.Batteries = await GetBatteries();
            mymodel.Columns = await GetColumns();
            mymodel.Elevators = await GetElevators();
            return View(mymodel);
        }
        //// GET: /<controller>/
        //public async Task<IActionResult> Index()
        //{
        //    List<Reservation> reservationList = new List<Reservation>();
        //    using (var httpClient = new HttpClient())
        //    {
        //        //HTTP GET request to the API
        //        using (var response = await httpClient.GetAsync("https://localhost:44324/api/Reservation"))
        //        {
        //            //data returned by the API is fetched from the code
        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //            //Deserialize the JSON to a List type object
        //            reservationList = JsonConvert.DeserializeObject<List<Reservation>>(apiResponse);
        //        }
        //    }
        //    return View(reservationList);
        //}

        // CUSTOMERS
        //public async Task<IActionResult> Index()
        //{
        //    List<Customer> customerList = new List<Customer>();
        //    using (var httpClient = new HttpClient())
        //    {
        //        //HTTP GET request to the API
        //        using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/interventions/pending"))
        //        {
        //            //data returned by the API is fetched from the code
        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //            //Deserialize the JSON to a List type object
        //            customerList = JsonConvert.DeserializeObject<List<Customer>>(apiResponse);
        //        }
        //    }
        //    return View(customerList);
        //}

        // BUILDINGS
        public async Task<IEnumerable<Building>> GetBuildings()
        {
            List<Building> buildingList = new List<Building>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/buildings"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    buildingList = JsonConvert.DeserializeObject<List<Building>>(apiResponse);
                }
            }
            return buildingList;
        }
        // BATTERIES
        public async Task<IEnumerable<Battery>> GetBatteries()
        {
            List<Battery> batteryList = new List<Battery>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/batteries"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    batteryList = JsonConvert.DeserializeObject<List<Battery>>(apiResponse);
                }
            }
            return batteryList;
        }
        // COLUMNS
        public async Task<IEnumerable<Column>> GetColumns()
        {
            List<Column> columnList = new List<Column>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/columns"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    columnList = JsonConvert.DeserializeObject<List<Column>>(apiResponse);
                }
            }
            return columnList;
        }
        // ELEVATORS
        public async Task<IEnumerable<Elevator>> GetElevators()
        {
            List<Elevator> elevatorList = new List<Elevator>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/elevators"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    elevatorList = JsonConvert.DeserializeObject<List<Elevator>>(apiResponse);
                }
            }
            return elevatorList;
        }
        ////CUSTOMER LOGGED IN
        //public async Task<IEnumerable<Customer>> FetchCustomer()
        //{
        //    using (var httpClient = new HttpClient())
        //    {
        //        //HTTP GET request to the API
        //        using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/customers"))
        //        {
        //            //data returned by the API is fetched from the code
        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //            //Deserialize the JSON to a List type object
        //            Customer customer = JsonConvert.DeserializeObject<Customer>(apiResponse);

        //        }
        //    }
        //    return customer;
        //}
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Net.Http;
using Newtonsoft.Json;
using rocket_elevators_customer_portal.Models;
using System.Dynamic;
using System.Net.Http.Headers;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace rocket_elevators_customer_portal.Controllers
{
    // [Authorize]
    
    public class ProductController : Controller
    {
        public async Task<IActionResult> IndexAsync()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.Batteries = await GetBatteries();
            mymodel.Columns = await GetColumns();
            mymodel.Elevators = await GetElevators();
            mymodel.Customer = await GetAccount();
            mymodel.Address = await GetAddress();
            mymodel.Building = await GetBuildings();
            return View(mymodel);
        }
        
        // Customers
        public async Task<IEnumerable<Customer>> GetAccount()
        {
            List<Customer> customerList = new List<Customer>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/customers"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    customerList = JsonConvert.DeserializeObject<List<Customer>>(apiResponse);
                }
            }
            return customerList;
        }

        // Address
        public async Task<IEnumerable<Address>> GetAddress()
        {
            List<Address> addressList = new List<Address>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/addresses"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    addressList = JsonConvert.DeserializeObject<List<Address>>(apiResponse);
                }
            }
            return addressList;
        }
        
        // BUILDINGS
        public async Task<IEnumerable<Building>> GetBuildings()
        {
            List<Building> buildingList = new List<Building>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/buildings"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    buildingList = JsonConvert.DeserializeObject<List<Building>>(apiResponse);
                }
            }
            return buildingList;
        }

        // BATTERIES
        public async Task<IEnumerable<Battery>> GetBatteries()
        {
            List<Battery> batteryList = new List<Battery>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/batteries"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    batteryList = JsonConvert.DeserializeObject<List<Battery>>(apiResponse);
                }
            }
            return batteryList;
        }

        // COLUMNS
        public async Task<IEnumerable<Column>> GetColumns()
        {
            List<Column> columnList = new List<Column>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/columns"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    columnList = JsonConvert.DeserializeObject<List<Column>>(apiResponse);
                }
            }
            return columnList;
        }

        // ELEVATORS
        public async Task<IEnumerable<Elevator>> GetElevators()
        {
            List<Elevator> elevatorList = new List<Elevator>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/elevators"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    elevatorList = JsonConvert.DeserializeObject<List<Elevator>>(apiResponse);
                }
            }
            return elevatorList;
        }

        //Update Contact Info
         // public async Task<Customer> ModifyContactInfo(int id)
         public async Task<IActionResult> ModifyContactInfo(int id)
        {
            Customer customer = new Customer();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/customers/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    customer = JsonConvert.DeserializeObject<Customer>(apiResponse);
                }
            }
            return View(customer);
        }
        
        // [HttpPost]
        // public async Task<Customer> ModifyContactInfo(Customer customer)
        // public async Task<IActionResult> ModifyContactInfo(Customer customer)
        // {
        //     Customer modifyCustomer = new Customer();
        //     using (var httpClient = new HttpClient())
        //     {
        //         var content = new MultipartFormDataContent();
        //         content.Add(new StringContent(customer.id.ToString()), "id");
        //         content.Add(new StringContent(customer.CompanyName), "CompanyName");
        //         content.Add(new StringContent(customer.NameOfContact), "NameOfContact");
        //         content.Add(new StringContent(customer.CompanyContactPhone), "CompanyContactPhone");
        //         content.Add(new StringContent(customer.EmailOfTheCompany), "EmailOfTheCompany");
        //         content.Add(new StringContent(customer.CompanyDescription), "CompanyDescription");
        //         content.Add(new StringContent(customer.NameOfServiceTechAuthority), "NameOfServiceTechAuthority");
        //         content.Add(new StringContent(customer.TechAuhtorityPhone), "TechAuhtorityPhone");
        //         content.Add(new StringContent(customer.TechManagerServiceEmail), "TechManagerServiceEmail");
        //
        //         using (var response = await httpClient.PutAsync("https://rocketapis.azurewebsites.net/api/customer", content))
        //         {
        //             string apiResponse = await response.Content.ReadAsStringAsync();
        //             ViewBag.Result = "Success";
        //             modifyCustomer = JsonConvert.DeserializeObject<Customer>(apiResponse);
        //         }
        //     }
        //     return View(modifyCustomer);
        // }

        // TESTING V2
        // public async Task<IActionResult> ModifyContactInfo(Customer customer)
        // {
        //     Customer modifyCustomer = new Customer();
        //     HttpClient client = new HttpClient();
        //     client.BaseAddress = new Uri("https://rocketapis.azurewebsites.net");
        //     client.DefaultRequestHeaders
        //         .Accept
        //         .Add(new MediaTypeWithQualityHeaderValue("application/json")); //ACCEPT header
        //
        //     HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "api/customer");
        //     Console.WriteLine(request);
        //     request.Content = new StringContent("{\"companyName\",\"nameOfContact\"}",
        //         Encoding.UTF8,
        //         "application/json"); //CONTENT-TYPE header
        //
        //     client.SendAsync(request)
        //         .ContinueWith(responseTask => { Console.WriteLine("Response: {0}", responseTask.Result); });
        //     
        //     return View(modifyCustomer);
        // }

        //Update Address Info
          public async Task<IActionResult> ModifyAddressInfo(int id)
        {
            Address address = new Address();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://whispering-tundra-91467.herokuapp.com/api/addresses/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    address = JsonConvert.DeserializeObject<Address>(apiResponse);
                }
            }

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link href="dashboard.css" rel="stylesheet">
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" />
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager



@if (SignInManager.IsSignedIn(User))
{

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" asp-controller="Home" asp-action="Index">Rocket Elevators</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            @*<a class="nav-link px-3" href="#">Sign out</a>*@

            @* <div class="nav-link px-3">
                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nav-link btn btn-link text-light">Logout</button>
                </form>
            </div> *@

        </div>
    </div>
</header>
<div class="container-fluid">
    <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">
                            <span data-feather="home"></span>
                            Portal Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Intervention" asp-action="Index">
                            <span data-feather="file"></span>
                            Intervention
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Product" asp-action="Index">
                            <span data-feather="layers"></span>
                            Products
                        </a>
                    </li>
                    @* <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="users"></span>
                            Chat
                        </a>
                    </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link" href="#"> *@
                    @*         <span data-feather="bar-chart-2"></span> *@
                    @*         Reports *@
                    @*     </a> *@
                    @* </li> *@
                    @*<li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>*@
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Saved reports</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Current month
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Last quarter
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Social engagement
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Year-end
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
   
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Customer Portal</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group me-2">
                        <partial name="_LoginPartial" />
                        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                    </div>
                    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                        <span data-feather="calendar"></span>
                        This week
                    </button>
                </div>
            </div>

            <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

            <h3>Total Asset Count</h3>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th scope="col">Customer #</th>
                            <th scope="col">Buildings</th>
                            <th scope="col">Batteries</th>
                            <th scope="col">Columns</th>
                            <th scope="col">Elevators</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1,001</td>
                            <td>random</td>
                            <td>data</td>
                            <td>placeholder</td>
                            <td>text</td>
                        </tr>
                        <tr>
                            <td>1,002</td>
                            <td>placeholder</td>
                            <td>irrelevant</td>
                            <td>visual</td>
                            <td>layout</td>
                        </tr>
                        <tr>
                            <td>1,003</td>
                            <td>data</td>
                            <td>rich</td>
                            <td>dashboard</td>
                            <td>tabular</td>
                        </tr>
                        <tr>
                            <td>1,003</td>
                            <td>information</td>
                            <td>placeholder</td>
                            <td>illustrative</td>
                            <td>data</td>
                        </tr>
                        <tr>
                            <td>1,004</td>
                            <td>text</td>
                            <td>random</td>
                            <td>layout</td>
                            <td>dashboard</td>
                        </tr>
                        <tr>
                            <td>1,005</td>
                            <td>dashboard</td>
                            <td>irrelevant</td>
                            <td>text</td>
                            <td>placeholder</td>
                        </tr>
                        <tr>
                            <td>1,006</td>
                            <td>dashboard</td>
                            <td>illustrative</td>
                            <td>rich</td>
                            <td>data</td>
                        </tr>
                        <tr>
                            <td>1,007</td>
                            <td>placeholder</td>
                            <td>tabular</td>
                            <td>information</td>
                            <td>irrelevant</td>
                        </tr>
                        <tr>
                            <td>1,008</td>
                            <td>random</td>
                            <td>data</td>
                            <td>placeholder</td>
                            <td>text</td>
                        </tr>
                        <tr>
                            <td>1,009</td>
                            <td>placeholder</td>
                            <td>irrelevant</td>
                            <td>visual</td>
                            <td>layout</td>
                        </tr>
                        <tr>
                            <td>1,010</td>
                            <td>data</td>
                            <td>rich</td>
                            <td>dashboard</td>
                            <td>tabular</td>
                        </tr>
                        <tr>
                            <td>1,011</td>
                            <td>information</td>
                            <td>placeholder</td>
                            <td>illustrative</td>
                            <td>data</td>
                        </tr>
                        <tr>
                            <td>1,012</td>
                            <td>text</td>
                            <td>placeholder</td>
                            <td>layout</td>
                            <td>dashboard</td>
                        </tr>
                        <tr>
                            <td>1,013</td>
                            <td>dashboard</td>
                            <td>irrelevant</td>
                            <td>text</td>
                            <td>visual</td>
                        </tr>
                        <tr>
                            <td>1,014</td>
                            <td>dashboard</td>
                            <td>illustrative</td>
                            <td>rich</td>
                            <td>data</td>
                        </tr>
                        <tr>
                            <td>1,015</td>
                            <td>random</td>
                            <td>tabular</td>
                            <td>information</td>
                            <td>text</td>
                        </tr>
                    </tbody>
                </table>
            </div>
<p class="mt-5 mb-3 text-muted">&copy; Site by Perry Sawatzky</p>
        </main>
         </div>
</div>
}
else {
 <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/signin.css" />
 <body class="text-center">
    <main class="form-signin">
        <form id="account" method="post">
            <img class="mb-4" src="~/img/rocket-logo.png" alt="Rocket Elevators logo" width="170" height="77">
            <h1 class="h3 mb-3 fw-normal">Customer Portal</h1>
           
            <partial name="_LoginPartial" />
            
            
            
            <p class="mt-5 mb-3 text-muted">&copy; Site by Perry Sawatzky</p>
        </form>
    </main>
</body>   
}
@*     </div> *@
@* </div> *@


<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" crossorigin="anonymous"></script>
<script src="~/js/dashboard.js"></script>

@* Useless, keeping incase I need to copy any of the syntax *@
@* <div class="text-center">
    <h1 class="display-4">Rocket Elevators Home Page</h1>
    <partial name="_LoginPartial" />
    
    <h1>Below</h1>
    
    <form asp-controller="Demo" asp-action="Register" method="post">
    <!-- Input and Submit elements -->
</form>
<form method="post" >
    <input name="__RequestVerificationToken" asp-fragment="email" value="">
    <button type='submit'>Validate</button>    
</form>
    
    <a asp-action="index" asp-controller="Intervention">Intervention Form</a>
    <a asp-action="profile" asp-controller="Intervention">Customer Profile</a>


    
</div> *@